### ISSUE TITLE
Acceptance testing i sprint 2

### ISSUE THREAD

**Issue by KiraStaehr** [cs-22-sw-5-15/report#13]
Flyttes væk fra sprint 2, hvis vi ik har lavet det

**Comment by alexsteffensen** [comment]
Er flyttet til en separat .tex fil i 02-analysis indtil det skal bruges

**Comment by MJHC** [comment]
Moved acceptance-testing.tex to 06-test-and-evaluation/

**Comment by MJHC** [comment]
Moved acceptance-testing.tex to 06-test-and-evaluation/
