### ISSUE TITLE
Martijn rettelser

### ISSUE THREAD

**Issue by KiraStaehr** [cs-22-sw-5-15/report#25]

**Comment by KiraStaehr** [comment]
Chapter 1 fra toppen: Simon
1.1.7 og op: Kira
1.3 og ned: Magnus
1.4 og ned: Loppe
Sprint 1: Alex

**Comment by alexsteffensen** [comment]
1.1.6 er færdig. går igang med 1.1.5

**Comment by alexsteffensen** [comment]
1.1.5 er færdig, går i gang med 1.1.4

**Comment by MJHC** [comment]
1.3 Done
